-- wei3（第二個場地）版本：描述 Supabase 專案裡 wei3 schema 的結構，內容跟原本場地
-- （sky03104/wei 資料庫版）一樣。
-- 注意：檔案裡沒寫 schema 名稱，直接貼到 SQL editor 跑會改到原本場地（public）！
-- 要改 wei3 請照 README.md「之後要改 wei3 的資料庫函式」的步驟。

-- supabase/schema.sql
--
-- Postgres schema for the claw-machine-manager backend, translated from the
-- Google Sheets structure defined in apps-script/Db.gs (SCHEMA / HEADER_LABELS).
-- This is phase 1 of the Supabase migration (see supabase/MIGRATION_PLAN.md).
--
-- Auth decision (locked in): frontend connects directly to Supabase, auth is
-- Supabase Auth, authorization is Row Level Security (see supabase/policies.sql).
-- That decision changes two tables from a 1:1 Sheets translation:
--   - `users` (username/password_hash/salt/session token) is GONE. Supabase
--     Auth's own `auth.users` owns credentials and sessions now. A `profiles`
--     table below carries only the app-specific fields (username, display
--     name, role, status) and is keyed by `auth.users.id`.
--   - `sessions` is GONE — Supabase Auth issues and validates its own JWTs,
--     apps-script/Auth.gs's hand-rolled token table has no equivalent to
--     migrate.
--   Login is by username in the current app, but Supabase Auth identifies
--   accounts by email. See "username login" in MIGRATION_PLAN.md and the
--   resolve_username_email() function in policies.sql for how that's bridged
--   without exposing the users table to anonymous callers.
--
-- Everything else keeps the existing text ids (e.g. 'mch_xxxxx', generated by
-- newId() in Db.gs) instead of switching to uuid — the current codebase
-- generates and compares these ids as strings everywhere, and there is no
-- reason to also rewrite id generation while also rewriting storage. Only
-- user-referencing columns become uuid, because they now point at
-- auth.users.id (which Supabase generates as uuid, not something this app
-- controls).
--
-- No archiving/partitioning table split (the "封存_2026Q1" style extra
-- sheets in Db.gs/Archive.gs) — that trick existed purely to work around
-- Sheets reading the whole table on every request. A real database with
-- indexes on (machine_id, business_date) does not need it; records just
-- stays one table forever. carry_in/out/prize/chip_in/chip_out columns on
-- machines are kept for the migration itself (see MIGRATION_PLAN.md) but the
-- running system will not need to add to them going forward.

-- ── profiles（app 端的使用者資料；帳密/session 交給 Supabase Auth）──
--
-- 一個 auth.users 對一個 profiles，1:1。角色／狀態／顯示名稱是 app 自己
-- 的概念，Supabase Auth 完全不知道，放在這裡。

create table if not exists profiles (
  id             uuid primary key references auth.users(id) on delete cascade,
  username       text not null unique,
  display_name   text not null default '',
  role           text not null check (role in ('admin', 'patrol', 'owner')),
  status         text not null default 'active' check (status in ('active', 'disabled')),
  created_at     timestamptz not null default now(),
  last_login_at  timestamptz
);

-- ── machines ────────────────────────────────────────────

create table if not exists machines (
  machine_id      text primary key,
  name            text not null,
  location        text not null default '',
  status          text not null default 'running' check (status in ('running', 'maintenance', 'offline')),
  color           text not null default '#4F7BE8',
  sort_order      numeric not null default 0,
  note            text not null default '',
  created_at      timestamptz not null default now(),
  category        text not null default 'dice' check (category in ('dice', 'electronic')),
  icon            text not null default 'classic',
  -- 封存前累計——遷移用欄位，見上面的說明；遷移完成、Records 全部搬進來
  -- 之後這幾欄只是歷史保留，程式邏輯不會再往上加。
  carry_in        numeric not null default 0,
  carry_out       numeric not null default 0,
  carry_prize     numeric not null default 0,
  carry_chip_in   numeric not null default 0,
  carry_chip_out  numeric not null default 0
);

-- ── records（單一最重要、資料量最大的表；所有查詢熱點都靠索引）──

create table if not exists records (
  -- 插入順序的決勝點，對應 apps-script/Db.gs dbReadAll() 附掛的 _row（試算
  -- 表列號）——GAS 那邊排序「最新一筆」（例如撈上一次入幣的下班表）用
  -- _byCreatedAtDesc()：created_at 字串比較，同一毫秒才用 _row 決勝。
  -- Postgres 沒有天然的「實體列號」，用 bigserial 給每一列一個嚴格遞增的
  -- 插入序號，效果相同。
  seq            bigserial,
  record_id      text primary key,
  machine_id     text not null references machines(machine_id),
  type           text not null check (type in ('in', 'out', 'prize', 'chip_in', 'chip_out')),
  amount         numeric not null default 0,
  prize_id       text,
  prize_name     text not null default '',
  unit_amount    numeric,
  count          numeric,
  user_id        uuid not null references profiles(id),
  created_at     timestamptz not null default now(),
  note           text not null default '',
  voided         boolean not null default false,
  voided_by      uuid references profiles(id),
  voided_at      timestamptz,
  client_token   text, -- 冪等鍵，對應 addRecord 的 clientToken 去重機制。
    -- 刻意不設 unique：addPrizeRecord 一次送多個獎型會用「同一個 client_token」
    -- 寫入好幾列（跟 GAS/Sheets 版本一致，Sheets 本來就沒有唯一約束），
    -- 去重靠 add_record()/add_prize_record() 裡先 select 再 insert 的
    -- app 層檢查（對照 _findByClientToken），不是靠資料庫約束。
  meter_start    numeric,
  meter_end      numeric,
  business_date  date not null -- 記帳當下 snapshot 好的營業日期，見 Service.gs 的 _currentBusinessDate()
);

-- 熱路徑：dashboard/machineDetail/report 幾乎每一支都是「某機台 + 某日期
-- 區間」，這支索引取代掉原本 Sheets 靠季度封存縮小表格的整套機制。
create index if not exists records_machine_business_date_idx
  on records (machine_id, business_date);
-- 「不看哪一台機台、全部機台合併算」的查詢（report 不指定 machineId、
-- 或 exportLedgerGrids 那種分類查詢）用得到。
create index if not exists records_business_date_idx
  on records (business_date);
create index if not exists records_voided_idx
  on records (voided) where voided = false;
create index if not exists records_client_token_idx
  on records (client_token) where client_token is not null and client_token <> '';

-- ── prizes ──────────────────────────────────────────────

create table if not exists prizes (
  prize_id    text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 meter_rates 一樣不能設外鍵（'' 不是真的機台）
  name        text not null,
  amount      numeric not null default 0,
  sort_order  numeric not null default 0,
  active      boolean not null default true
);

create index if not exists prizes_machine_idx on prizes (machine_id);

-- ── quick_amounts ───────────────────────────────────────

create table if not exists quick_amounts (
  qa_id       text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 meter_rates 一樣不能設外鍵（'' 不是真的機台）
  type        text not null check (type in ('in', 'out')),
  amount      numeric not null,
  label       text not null default '',
  sort_order  numeric not null default 0
);

create index if not exists quick_amounts_machine_idx on quick_amounts (machine_id);

-- ── meter_rates ─────────────────────────────────────────

create table if not exists meter_rates (
  rate_id     text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 Db.gs 原本的用法一致
  rate        numeric not null default 100
);

create index if not exists meter_rates_machine_idx on meter_rates (machine_id);

-- ── permissions（台主看得到哪些機台；RLS policy 的判斷依據）──

create table if not exists permissions (
  user_id      uuid not null references profiles(id),
  machine_id   text not null references machines(machine_id),
  granted_by   uuid references profiles(id),
  granted_at   timestamptz not null default now(),
  primary key (user_id, machine_id)
);

-- ── config（系統設定，key-value）─────────────────────────

create table if not exists config (
  key    text primary key,
  value  text not null default ''
);

-- ── biz_days（手動營業日 session，處理跨夜）──────────────

create table if not exists biz_days (
  seq            bigserial, -- 插入順序決勝點，見 records.seq 的說明
  biz_id         text primary key,
  business_date  date not null,
  opened_at      timestamptz not null,
  opened_by      uuid references profiles(id),
  closed_at      timestamptz,
  closed_by      uuid references profiles(id),
  auto_closed    boolean not null default false
);

create index if not exists biz_days_open_idx on biz_days (closed_at) where closed_at is null;
create index if not exists biz_days_business_date_idx on biz_days (business_date);
-- 同一時間最多一筆進行中的營業日——對照 GAS 版本 startBusinessDay()／
-- endBusinessDay() 靠 withLock() 這個全域鎖序列化「開始一筆前先把前一筆
-- 結掉」這個檢查再寫入的過程；Postgres 沒有等價的全域鎖，改用「常數
-- expression 的 partial unique index」讓資料庫自己保證這個不變量：
-- 兩個人同時按「開始」，其中一個的 insert 會直接撞到這個唯一索引丟出
-- unique_violation，不會悄悄產生兩筆同時「進行中」的營業日。
create unique index if not exists biz_days_single_open_idx on biz_days ((true)) where closed_at is null;

-- ── daily_ledger（每日手動帳目：週轉金／台主給／台主領…）─

create table if not exists daily_ledger (
  seq                    bigserial, -- 插入順序決勝點，見 records.seq 的說明
  ledger_id              text primary key,
  business_date          date not null,
  turnover               numeric not null default 0,
  transport              numeric not null default 0, -- 舊欄位，已經用不到，保留讀舊資料
  given_to_owner         numeric not null default 0,  -- 舊欄位，已改用 given_to_owner_items
  taken_by_owner         numeric not null default 0,  -- 舊欄位，已改用 taken_by_owner_items
  returned_to_house      numeric not null default 0,  -- 舊欄位，已經用不到，保留讀舊資料
  updated_by             uuid references profiles(id),
  updated_at             timestamptz not null default now(),
  biz_id                 text references biz_days(biz_id),
  manual_432             numeric not null default 0,
  manual_441             numeric not null default 0,
  given_to_owner_items   jsonb not null default '[]'::jsonb, -- [{name, amount}, ...]
  taken_by_owner_items   jsonb not null default '[]'::jsonb,
  manual_expense         numeric not null default 0
);

create index if not exists daily_ledger_business_date_idx on daily_ledger (business_date);
-- 「每個營業日 session 只存一組，重複儲存是覆蓋不是疊加」的不變量，
-- 對照 GAS 版本 saveDailyLedger() 靠 withLock() 序列化「先查有沒有現成
-- 那列、有就 update、沒有才 insert」這個檢查再寫入的過程。這裡改用
-- unique index + save_daily_ledger()（functions.sql）裡的
-- insert ... on conflict do update，資料庫層面直接保證不會有兩人同時
-- 儲存時各自 insert 出兩列的競態問題。biz_id 可能是 null（沒有相關營業日
-- session 時），用 coalesce 轉成空字串才能放進 unique index——null 在
-- Postgres 唯一索引裡永遠被視為互不相同，不轉换的話多筆 biz_id 都是
-- null、business_date 相同的列不會被這個索引擋下來。
create unique index if not exists daily_ledger_one_per_biz_day_idx
  on daily_ledger (business_date, (coalesce(biz_id, '')));

-- ── Row Level Security ──────────────────────────────────
--
-- 開啟但不在這支檔案寫 policy——policy 邏輯（含要用到的 helper function：
-- current_role()／can_record()／can_see_machine()）另外放在
-- supabase/policies.sql，schema 定義跟權限規則分開維護，改權限不用重跑
-- 整份建表腳本。RLS 預設就是全擋，這裡先開啟是安全的起始狀態，
-- policies.sql 沒套用之前，任何角色都讀不到、寫不進任何一張表。

alter table profiles         enable row level security;
alter table machines         enable row level security;
alter table records          enable row level security;
alter table prizes           enable row level security;
alter table quick_amounts    enable row level security;
alter table meter_rates      enable row level security;
alter table permissions      enable row level security;
alter table config           enable row level security;
alter table biz_days         enable row level security;
alter table daily_ledger     enable row level security;
