-- supabase/wei3_setup.sql
--
-- 第二個場地（wei3）的資料庫：跟原本場地共用同一個 Supabase 專案（gwwuzmspgvpzlstvafov），
-- 但所有資料表、函式、權限規則都放在獨立的 wei3 schema，資料完全分開。
--   - 前端（docs/config.js）設 SUPABASE_SCHEMA: 'wei3'，supabase-js 的每個查詢／rpc 都只打 wei3。
--   - 結構 = 原本資料庫版的 supabase/schema.sql + policies.sql + functions.sql（這個 repo 的
--     supabase/ 底下有一樣的三個檔案可以對照），差別只有：建在 wei3、每支函式的
--     search_path 固定成 wei3。不含 webhook-trigger.sql（同步 Google 試算表用的，wei3 沒有試算表）。
--   - 帳號：Supabase Auth（auth.users）整個專案共用，但 wei3 有自己的 wei3.profiles 帳號名單，
--     email 用 @wei3.local（原本場地是 @migrated.local），兩邊可以有同名帳號。原本場地的帳號
--     在 wei3.profiles 查不到，登入 wei3 什麼都看不到、什麼都做不了（反過來也一樣）。
--   - 整段包在一個 DO 區塊裡：中間任何一步失敗，整段都不會留下來。
--
-- 套用後還要在 Supabase 後台 Project Settings → Data API → Exposed schemas 加上 wei3，
-- 前端才連得到。

do $wei3$
declare
  _fn record;
  _def text;
  _pos int;
  _head text;
begin
  -- ── wei3 schema 與權限（跟 public 一樣：anon/authenticated/service_role 可用，實際擋人的是 RLS 與函式裡的檢查）──
  create schema if not exists wei3;
  comment on schema wei3 is '第二個場地（GitHub: sky03104/wei3）。資料跟原本場地（public）完全分開。';
  grant usage on schema wei3 to anon, authenticated, service_role;
  alter default privileges for role postgres in schema wei3 grant all on tables to anon, authenticated, service_role;
  alter default privileges for role postgres in schema wei3 grant all on routines to anon, authenticated, service_role;
  alter default privileges for role postgres in schema wei3 grant all on sequences to anon, authenticated, service_role;

  -- 下面 schema.sql／policies.sql 的內容都沒寫 schema 名稱，靠 search_path 讓它們建在 wei3。
  -- 再確認一次真的切過去了，絕不能建到原本場地（public）。
  perform set_config('search_path', 'wei3, pg_temp', true);
  if current_schema() is distinct from 'wei3' then
    raise exception '目前 schema 是 %，不是 wei3，中止', current_schema();
  end if;

  -- ════════ schema.sql（原樣）════════
-- supabase/schema.sql
--
-- Postgres schema for the claw-machine-manager backend, translated from the
-- Google Sheets structure defined in apps-script/Db.gs (SCHEMA / HEADER_LABELS).
-- This is phase 1 of the Supabase migration (see supabase/MIGRATION_PLAN.md).
--
-- Auth decision (locked in): frontend connects directly to Supabase, auth is
-- Supabase Auth, authorization is Row Level Security (see supabase/policies.sql).
-- That decision changes two tables from a 1:1 Sheets translation:
--   - `users` (username/password_hash/salt/session token) is GONE. Supabase
--     Auth's own `auth.users` owns credentials and sessions now. A `profiles`
--     table below carries only the app-specific fields (username, display
--     name, role, status) and is keyed by `auth.users.id`.
--   - `sessions` is GONE — Supabase Auth issues and validates its own JWTs,
--     apps-script/Auth.gs's hand-rolled token table has no equivalent to
--     migrate.
--   Login is by username in the current app, but Supabase Auth identifies
--   accounts by email. See "username login" in MIGRATION_PLAN.md and the
--   resolve_username_email() function in policies.sql for how that's bridged
--   without exposing the users table to anonymous callers.
--
-- Everything else keeps the existing text ids (e.g. 'mch_xxxxx', generated by
-- newId() in Db.gs) instead of switching to uuid — the current codebase
-- generates and compares these ids as strings everywhere, and there is no
-- reason to also rewrite id generation while also rewriting storage. Only
-- user-referencing columns become uuid, because they now point at
-- auth.users.id (which Supabase generates as uuid, not something this app
-- controls).
--
-- No archiving/partitioning table split (the "封存_2026Q1" style extra
-- sheets in Db.gs/Archive.gs) — that trick existed purely to work around
-- Sheets reading the whole table on every request. A real database with
-- indexes on (machine_id, business_date) does not need it; records just
-- stays one table forever. carry_in/out/prize/chip_in/chip_out columns on
-- machines are kept for the migration itself (see MIGRATION_PLAN.md) but the
-- running system will not need to add to them going forward.

-- ── profiles（app 端的使用者資料；帳密/session 交給 Supabase Auth）──
--
-- 一個 auth.users 對一個 profiles，1:1。角色／狀態／顯示名稱是 app 自己
-- 的概念，Supabase Auth 完全不知道，放在這裡。

create table if not exists profiles (
  id             uuid primary key references auth.users(id) on delete cascade,
  username       text not null unique,
  display_name   text not null default '',
  role           text not null check (role in ('admin', 'patrol', 'owner')),
  status         text not null default 'active' check (status in ('active', 'disabled')),
  created_at     timestamptz not null default now(),
  last_login_at  timestamptz
);

-- ── machines ────────────────────────────────────────────

create table if not exists machines (
  machine_id      text primary key,
  name            text not null,
  location        text not null default '',
  status          text not null default 'running' check (status in ('running', 'maintenance', 'offline')),
  color           text not null default '#4F7BE8',
  sort_order      numeric not null default 0,
  note            text not null default '',
  created_at      timestamptz not null default now(),
  category        text not null default 'dice' check (category in ('dice', 'electronic')),
  icon            text not null default 'classic',
  -- 封存前累計——遷移用欄位，見上面的說明；遷移完成、Records 全部搬進來
  -- 之後這幾欄只是歷史保留，程式邏輯不會再往上加。
  carry_in        numeric not null default 0,
  carry_out       numeric not null default 0,
  carry_prize     numeric not null default 0,
  carry_chip_in   numeric not null default 0,
  carry_chip_out  numeric not null default 0
);

-- ── records（單一最重要、資料量最大的表；所有查詢熱點都靠索引）──

create table if not exists records (
  -- 插入順序的決勝點，對應 apps-script/Db.gs dbReadAll() 附掛的 _row（試算
  -- 表列號）——GAS 那邊排序「最新一筆」（例如撈上一次入幣的下班表）用
  -- _byCreatedAtDesc()：created_at 字串比較，同一毫秒才用 _row 決勝。
  -- Postgres 沒有天然的「實體列號」，用 bigserial 給每一列一個嚴格遞增的
  -- 插入序號，效果相同。
  seq            bigserial,
  record_id      text primary key,
  machine_id     text not null references machines(machine_id),
  type           text not null check (type in ('in', 'out', 'prize', 'chip_in', 'chip_out')),
  amount         numeric not null default 0,
  prize_id       text,
  prize_name     text not null default '',
  unit_amount    numeric,
  count          numeric,
  user_id        uuid not null references profiles(id),
  created_at     timestamptz not null default now(),
  note           text not null default '',
  voided         boolean not null default false,
  voided_by      uuid references profiles(id),
  voided_at      timestamptz,
  client_token   text, -- 冪等鍵，對應 addRecord 的 clientToken 去重機制。
    -- 刻意不設 unique：addPrizeRecord 一次送多個獎型會用「同一個 client_token」
    -- 寫入好幾列（跟 GAS/Sheets 版本一致，Sheets 本來就沒有唯一約束），
    -- 去重靠 add_record()/add_prize_record() 裡先 select 再 insert 的
    -- app 層檢查（對照 _findByClientToken），不是靠資料庫約束。
  meter_start    numeric,
  meter_end      numeric,
  business_date  date not null -- 記帳當下 snapshot 好的營業日期，見 Service.gs 的 _currentBusinessDate()
);

-- 熱路徑：dashboard/machineDetail/report 幾乎每一支都是「某機台 + 某日期
-- 區間」，這支索引取代掉原本 Sheets 靠季度封存縮小表格的整套機制。
create index if not exists records_machine_business_date_idx
  on records (machine_id, business_date);
-- 「不看哪一台機台、全部機台合併算」的查詢（report 不指定 machineId、
-- 或 exportLedgerGrids 那種分類查詢）用得到。
create index if not exists records_business_date_idx
  on records (business_date);
create index if not exists records_voided_idx
  on records (voided) where voided = false;
create index if not exists records_client_token_idx
  on records (client_token) where client_token is not null and client_token <> '';

-- ── prizes ──────────────────────────────────────────────

create table if not exists prizes (
  prize_id    text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 meter_rates 一樣不能設外鍵（'' 不是真的機台）
  name        text not null,
  amount      numeric not null default 0,
  sort_order  numeric not null default 0,
  active      boolean not null default true
);

create index if not exists prizes_machine_idx on prizes (machine_id);

-- ── quick_amounts ───────────────────────────────────────

create table if not exists quick_amounts (
  qa_id       text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 meter_rates 一樣不能設外鍵（'' 不是真的機台）
  type        text not null check (type in ('in', 'out')),
  amount      numeric not null,
  label       text not null default '',
  sort_order  numeric not null default 0
);

create index if not exists quick_amounts_machine_idx on quick_amounts (machine_id);

-- ── meter_rates ─────────────────────────────────────────

create table if not exists meter_rates (
  rate_id     text primary key,
  machine_id  text not null default '', -- 空字串＝全局預設，跟 Db.gs 原本的用法一致
  rate        numeric not null default 100
);

create index if not exists meter_rates_machine_idx on meter_rates (machine_id);

-- ── permissions（台主看得到哪些機台；RLS policy 的判斷依據）──

create table if not exists permissions (
  user_id      uuid not null references profiles(id),
  machine_id   text not null references machines(machine_id),
  granted_by   uuid references profiles(id),
  granted_at   timestamptz not null default now(),
  primary key (user_id, machine_id)
);

-- ── config（系統設定，key-value）─────────────────────────

create table if not exists config (
  key    text primary key,
  value  text not null default ''
);

-- ── biz_days（手動營業日 session，處理跨夜）──────────────

create table if not exists biz_days (
  seq            bigserial, -- 插入順序決勝點，見 records.seq 的說明
  biz_id         text primary key,
  business_date  date not null,
  opened_at      timestamptz not null,
  opened_by      uuid references profiles(id),
  closed_at      timestamptz,
  closed_by      uuid references profiles(id),
  auto_closed    boolean not null default false
);

create index if not exists biz_days_open_idx on biz_days (closed_at) where closed_at is null;
create index if not exists biz_days_business_date_idx on biz_days (business_date);
-- 同一時間最多一筆進行中的營業日——對照 GAS 版本 startBusinessDay()／
-- endBusinessDay() 靠 withLock() 這個全域鎖序列化「開始一筆前先把前一筆
-- 結掉」這個檢查再寫入的過程；Postgres 沒有等價的全域鎖，改用「常數
-- expression 的 partial unique index」讓資料庫自己保證這個不變量：
-- 兩個人同時按「開始」，其中一個的 insert 會直接撞到這個唯一索引丟出
-- unique_violation，不會悄悄產生兩筆同時「進行中」的營業日。
create unique index if not exists biz_days_single_open_idx on biz_days ((true)) where closed_at is null;

-- ── daily_ledger（每日手動帳目：週轉金／台主給／台主領…）─

create table if not exists daily_ledger (
  seq                    bigserial, -- 插入順序決勝點，見 records.seq 的說明
  ledger_id              text primary key,
  business_date          date not null,
  turnover               numeric not null default 0,
  transport              numeric not null default 0, -- 舊欄位，已經用不到，保留讀舊資料
  given_to_owner         numeric not null default 0,  -- 舊欄位，已改用 given_to_owner_items
  taken_by_owner         numeric not null default 0,  -- 舊欄位，已改用 taken_by_owner_items
  returned_to_house      numeric not null default 0,  -- 舊欄位，已經用不到，保留讀舊資料
  updated_by             uuid references profiles(id),
  updated_at             timestamptz not null default now(),
  biz_id                 text references biz_days(biz_id),
  manual_432             numeric not null default 0,
  manual_441             numeric not null default 0,
  given_to_owner_items   jsonb not null default '[]'::jsonb, -- [{name, amount}, ...]
  taken_by_owner_items   jsonb not null default '[]'::jsonb,
  manual_expense         numeric not null default 0
);

create index if not exists daily_ledger_business_date_idx on daily_ledger (business_date);
-- 「每個營業日 session 只存一組，重複儲存是覆蓋不是疊加」的不變量，
-- 對照 GAS 版本 saveDailyLedger() 靠 withLock() 序列化「先查有沒有現成
-- 那列、有就 update、沒有才 insert」這個檢查再寫入的過程。這裡改用
-- unique index + save_daily_ledger()（functions.sql）裡的
-- insert ... on conflict do update，資料庫層面直接保證不會有兩人同時
-- 儲存時各自 insert 出兩列的競態問題。biz_id 可能是 null（沒有相關營業日
-- session 時），用 coalesce 轉成空字串才能放進 unique index——null 在
-- Postgres 唯一索引裡永遠被視為互不相同，不轉换的話多筆 biz_id 都是
-- null、business_date 相同的列不會被這個索引擋下來。
create unique index if not exists daily_ledger_one_per_biz_day_idx
  on daily_ledger (business_date, (coalesce(biz_id, '')));

-- ── Row Level Security ──────────────────────────────────
--
-- 開啟但不在這支檔案寫 policy——policy 邏輯（含要用到的 helper function：
-- current_role()／can_record()／can_see_machine()）另外放在
-- supabase/policies.sql，schema 定義跟權限規則分開維護，改權限不用重跑
-- 整份建表腳本。RLS 預設就是全擋，這裡先開啟是安全的起始狀態，
-- policies.sql 沒套用之前，任何角色都讀不到、寫不進任何一張表。

alter table profiles         enable row level security;
alter table machines         enable row level security;
alter table records          enable row level security;
alter table prizes           enable row level security;
alter table quick_amounts    enable row level security;
alter table meter_rates      enable row level security;
alter table permissions      enable row level security;
alter table config           enable row level security;
alter table biz_days         enable row level security;
alter table daily_ledger     enable row level security;

  -- ════════ policies.sql（helper 函式的 search_path 改成 wei3）════════
-- supabase/policies.sql
--
-- Row Level Security policies for the tables in supabase/schema.sql.
-- Run schema.sql first. This file assumes the "前端直連 + RLS" decision
-- (see MIGRATION_PLAN.md「Auth & RLS」): there is no backend API layer for
-- normal reads/writes — the frontend calls Supabase directly with the
-- signed-in user's JWT, and these policies are the only thing standing
-- between one user's data and another's. Get this file right before
-- pointing any real frontend code at a project using it.
--
-- Role model carried over 1:1 from apps-script/Code.gs's ACTION_ROLES /
-- apps-script/Service.gs's canRecord()/isAdmin()/visibleMachineIds():
--   admin   — sees and manages everything.
--   patrol  — sees and records against every machine, but can't manage
--             machines/prizes/quick-amounts/meter-rates/users/permissions
--             and can't void a record (that stays admin-only).
--   owner   — read-only, and only for machines explicitly granted via the
--             `permissions` table.

-- ── helper functions ────────────────────────────────────
--
-- security definer + fixed search_path so these can read `profiles` (which
-- itself has RLS enabled) without recursing into the RLS check they exist
-- to serve, and without being hijackable by a caller-controlled search_path.

-- 對照 GAS 的 validateSession()：帳號被停用之後，這個 session 剩下的
-- 有效期內也不該還能做任何事——GAS 版本每次 validateSession() 都會
-- 明確檢查 status，這裡對照的做法是讓 status 不是 active 時直接查不到
-- 任何 role（回傳 null），is_admin()/can_record()/can_see_machine()
-- 這些全部靠 current_role_name() 判斷的檢查就會自動全部擋下來，
-- 不用每個地方各自重複檢查一次 status。
create or replace function current_role_name()
returns text
language sql
stable
security definer
set search_path = wei3, pg_temp
as $$
  select role from profiles where id = auth.uid() and status = 'active';
$$;

-- coalesce(..., false) 是必要的，不是保險而已：帳號被停用時
-- current_role_name() 回傳 null，而 SQL 的 `null = 'admin'`／
-- `null in (...)` 算出來也是 null，不是 false。這些 helper function
-- 幾乎全部被拿去寫成 `if not is_admin() then raise ...` 這種 plpgsql
-- 判斷式，`if not null` 在 plpgsql 裡是 null、當成不成立處理，等於
-- 直接跳過那個檢查，沒有真的擋下來（RLS 本身用 `using (...)` 的
-- null 語意沒有這個問題，null 一樣不算通過，但這些 function 不是只
-- 用在 RLS policy，還被明確拿來當 plpgsql 的守門判斷用，兩邊語意
-- 不一樣，要用 coalesce 統一成真正的 boolean）。
create or replace function is_admin()
returns boolean
language sql
stable
security definer
set search_path = wei3, pg_temp
as $$
  select coalesce(current_role_name() = 'admin', false);
$$;

create or replace function can_record()
returns boolean
language sql
stable
security definer
set search_path = wei3, pg_temp
as $$
  select coalesce(current_role_name() in ('admin', 'patrol'), false);
$$;

-- 「看得到某台機台」＝管理員／巡邏人員一律看得到；台主要 permissions
-- 表裡有這一筆授權才算。跟 apps-script/Service.gs 的 visibleMachineIds()／
-- assertMachineAccess() 是同一套規則。
create or replace function can_see_machine(p_machine_id text)
returns boolean
language sql
stable
security definer
set search_path = wei3, pg_temp
as $$
  select coalesce(
    current_role_name() in ('admin', 'patrol')
    or exists (
      select 1 from permissions
      where permissions.machine_id = p_machine_id
        and permissions.user_id = auth.uid()
    ),
    false
  );
$$;

-- ── profiles ────────────────────────────────────────────

drop policy if exists profiles_select on profiles;
create policy profiles_select on profiles
  for select using (id = auth.uid() or is_admin());

-- 新增/停用帳號、改角色都是管理員的事（對照 adminSaveUser: [ROLE_ADMIN]）。
-- 帳號本身（email/密碼）是 auth.users 的事，不歸這裡管——新建帳號的流程
-- 見下面「新使用者要怎麼進系統」的說明，不是單純一筆 insert 就能做完。
drop policy if exists profiles_update on profiles;
create policy profiles_update on profiles
  for update using (is_admin());

-- ── machines ────────────────────────────────────────────

drop policy if exists machines_select on machines;
create policy machines_select on machines
  for select using (can_see_machine(machine_id));

drop policy if exists machines_write on machines;
create policy machines_write on machines
  for all using (is_admin()) with check (is_admin());

-- ── records ─────────────────────────────────────────────

drop policy if exists records_select on records;
create policy records_select on records
  for select using (can_see_machine(machine_id));

-- 新增紀錄：對照 addRecord/addPrizeRecord/addMeterRecord: [ROLE_ADMIN, ROLE_PATROL]。
-- 這兩個角色本來就看得到全部機台（can_see_machine 對他們一律回 true），
-- 這裡不用再另外判斷 machine_id。
drop policy if exists records_insert on records;
create policy records_insert on records
  for insert with check (can_record());

-- 作廢紀錄：對照 voidRecord: [ROLE_ADMIN]，只能改 voided/voided_by/voided_at
-- 這幾欄——實際「只能改這幾欄」要靠前端/應用層自律或另外寫 trigger 擋，
-- RLS 的 with check 管不到「只准改哪幾欄」，只能管「這一列准不准被改」。
drop policy if exists records_update on records;
create policy records_update on records
  for update using (is_admin()) with check (is_admin());

-- 沒有 delete policy：現有系統本來就沒有刪除紀錄的動作（作廢是 update
-- voided=true，不是真的刪列），RLS 預設擋掉，行為跟現在一致。

-- ── prizes／quick_amounts／meter_rates ──────────────────
--
-- 三張表同一種規則：machine_id 是空字串代表「全局預設」，任何登入的人
-- 都看得到（不含機台專屬資訊，看到也沒差）；有指定機台的話照
-- can_see_machine() 判斷。寫入（新增/改價/停用/刪除/複製全局到單台）
-- 一律管理員專屬，對照 savePrize/deletePrize/saveQuickAmount/
-- deleteQuickAmount/saveMeterRate/forkScope/resetScope: [ROLE_ADMIN]。

drop policy if exists prizes_select on prizes;
create policy prizes_select on prizes
  for select using (machine_id = '' or can_see_machine(machine_id));
drop policy if exists prizes_write on prizes;
create policy prizes_write on prizes
  for all using (is_admin()) with check (is_admin());

drop policy if exists quick_amounts_select on quick_amounts;
create policy quick_amounts_select on quick_amounts
  for select using (machine_id = '' or can_see_machine(machine_id));
drop policy if exists quick_amounts_write on quick_amounts;
create policy quick_amounts_write on quick_amounts
  for all using (is_admin()) with check (is_admin());

drop policy if exists meter_rates_select on meter_rates;
create policy meter_rates_select on meter_rates
  for select using (machine_id = '' or can_see_machine(machine_id));
drop policy if exists meter_rates_write on meter_rates;
create policy meter_rates_write on meter_rates
  for all using (is_admin()) with check (is_admin());

-- ── permissions ─────────────────────────────────────────
--
-- 對照 adminListPermissions／adminSetPermission: [ROLE_ADMIN]——現在的
-- 系統裡台主自己看不到「台主授權」這份清單本身（他只是被這份清單決定
-- 看不看得到某台機台），所以這裡完全不開放給非管理員。

drop policy if exists permissions_all on permissions;
create policy permissions_all on permissions
  for all using (is_admin()) with check (is_admin());

-- ── biz_days（今日營業開始／結單）────────────────────────
--
-- 讀取：dashboard 三種角色都會顯示營業日狀態，所以只要有登入就給讀。
-- 寫入：對照 startBusinessDay／endBusinessDay: [ROLE_ADMIN, ROLE_PATROL]。

drop policy if exists biz_days_select on biz_days;
create policy biz_days_select on biz_days
  for select using (auth.uid() is not null);
drop policy if exists biz_days_write on biz_days;
create policy biz_days_write on biz_days
  for all using (can_record()) with check (can_record());

-- ── daily_ledger（加總分頁的今日現金結餘明細）───────────
--
-- 讀取：dashboard 三種角色都看得到這份明細，所以只要有登入就給讀。
-- 寫入：對照 saveDailyLedger: [ROLE_ADMIN, ROLE_PATROL]。

drop policy if exists daily_ledger_select on daily_ledger;
create policy daily_ledger_select on daily_ledger
  for select using (auth.uid() is not null);
drop policy if exists daily_ledger_write on daily_ledger;
create policy daily_ledger_write on daily_ledger
  for all using (can_record()) with check (can_record());

-- ── config ──────────────────────────────────────────────
--
-- 舊系統存這裡的兩個鍵（last_archived_quarter／last_archived_at）是季度
-- 封存機制專用，這套機制在 Postgres 架構下不需要了（見 schema.sql／
-- MIGRATION_PLAN.md 的說明），這張表遷移過去很可能整個用不到。先鎖成
-- 管理員專屬，不開放給前端一般讀寫，之後真的確定用不到再考慮拿掉整張表。

drop policy if exists config_admin_only on config;
create policy config_admin_only on config
  for all using (is_admin()) with check (is_admin());

-- ── 新使用者要怎麼進系統（還沒實作，先記下來）────────────
--
-- 前端直連＋RLS 代表沒有一個像現在 adminSaveUser 那樣的後端 API 可以
-- 「建立帳號」——建立 Supabase Auth 使用者（auth.users）必須用
-- service role key 呼叫 Admin API（supabase.auth.admin.createUser()），
-- 這把 key 絕對不能出現在前端，代表「管理員新增帳號」這個動作勢必要
-- 一個小小的、有 service role 權限的後端（Edge Function 或其他伺服器）
-- 來做，不能是純前端直連——這是整個「前端直連＋RLS」方案裡唯一還是
-- 需要一小塊後端程式碼的地方，其餘的讀寫都可以純前端＋RLS 搞定。
--
-- 建議流程：
--   1. Edge Function（僅限 is_admin() 的呼叫者）用 service role 呼叫
--      auth.admin.createUser({ email: synthesizeEmail(username), password })。
--   2. 下面這個 trigger 在 auth.users 新增一列的當下，自動在 profiles
--      插入對應的一列（role/username 從 createUser() 的 user_metadata 帶過去），
--      管理員不用另外再手動呼叫一次 insert profiles。
--
-- create or replace function handle_new_user()
-- returns trigger
-- language plpgsql
-- security definer
-- set search_path = wei3, pg_temp
-- as $$
-- begin
--   insert into profiles (id, username, display_name, role)
--   values (
--     new.id,
--     new.raw_user_meta_data->>'username',
--     coalesce(new.raw_user_meta_data->>'display_name', ''),
--     coalesce(new.raw_user_meta_data->>'role', 'owner')
--   );
--   return new;
-- end;
-- $$;
--
-- create trigger on_auth_user_created
--   after insert on auth.users
--   for each row execute function handle_new_user();

-- ── username 登入怎麼接（還沒實作，先記下來）─────────────
--
-- Supabase Auth 認的是 email，現有系統的登入畫面是打帳號（username）+
-- 密碼，不是 email。做法：帳號建立時（見上面的 handle_new_user）幫每個
-- 使用者合成一個內部用、使用者自己不會看到也不用記得的 email，例如
-- `<username>@clawapp.internal`；登入畫面收到 username 之後，先用下面
-- 這支「未登入也能呼叫」的函式換回對應的 email，再拿 email+密碼呼叫
-- Supabase Auth 的 signInWithPassword()——多一次查詢，但使用者體感上
-- 感覺不出來（前端幫忙做這兩步，介面上維持「打帳號登入」不變）。
--
-- security definer 是必要的：呼叫這支函式的當下使用者根本還沒登入
-- （anon role），profiles／auth.users 的 RLS／權限一定擋得住 anon 直接
-- 查表，只能靠這支函式繞過去，但只回傳 email 這一個欄位，不會洩漏
-- 其他使用者資料。
--
-- Phase 5（docs/app.js 改接）已經要用到「打帳號登入」了，所以這支從
-- 草稿轉正、實際啟用（下面幾行不再是註解）。帳號不存在或帳號被停用都
-- 回傳 null（跟查得到但密碼打錯，前端看到的錯誤訊息要一樣，不能讓人
-- 從錯誤訊息猜出「這個帳號存不存在」）。
create or replace function resolve_username_email(p_username text)
returns text
language sql
security definer
set search_path = wei3, auth, pg_temp
as $$
  select au.email
  from profiles p
  join auth.users au on au.id = p.id
  where p.username = p_username
    and p.status = 'active';
$$;

grant execute on function resolve_username_email(text) to anon, authenticated;

-- 這支函式讀得到 auth.users，代表建立它的角色要有這個 schema 的存取
-- 權限——在 Supabase SQL editor 用專案自己的管理連線跑就沒問題，用一般
-- migration CLI 跑之前先確認權限，這塊在不同 Supabase 專案設定下偶爾
-- 會卡權限，值得先在測試專案跑一次確認沒問題再套用到別的環境。

  -- ════════ functions.sql：從原本場地目前的定義複製 ════════
  -- pg_get_functiondef 在 search_path 只有 pg_catalog 時，函式名稱、參數與回傳的資料表型別都會
  -- 寫成 public.xxx；只把宣告那段（AS 之前）的 public. 換成 wei3.，函式本體一字不動。
  -- 本體裡本來就沒有 public.（已確認），所以本體會繼續照 search_path 找資料表，下面再把
  -- 每支函式的 search_path 固定成 wei3。
  perform set_config('check_function_bodies', 'off', true);
  for _fn in
    select p.oid, p.proname
    from pg_proc p
    where p.pronamespace = 'public'::regnamespace
      and p.prokind = 'f'
      and p.proname <> 'notify_gas_webhook'   -- 原本場地同步 Google 試算表用的，wei3 沒有試算表
      and not exists (select 1 from pg_proc q where q.pronamespace = 'wei3'::regnamespace and q.proname = p.proname)
    order by p.oid
  loop
    perform set_config('search_path', 'pg_catalog', true);
    _def := pg_get_functiondef(_fn.oid);
    perform set_config('search_path', 'wei3, pg_temp', true);
    _pos := strpos(_def, E'\nAS $function$');
    if _pos = 0 or _def not like 'CREATE OR REPLACE FUNCTION public.%' then
      raise exception '函式 % 的格式不如預期，中止', _fn.proname;
    end if;
    _head := replace(left(_def, _pos), 'public.', 'wei3.');
    if _head ~ '\mpublic\M' then
      raise exception '函式 % 的宣告裡還有 public，中止', _fn.proname;
    end if;
    execute _head || substr(_def, _pos + 1);
  end loop;
  perform set_config('check_function_bodies', 'on', true);

  -- ── 每支函式的 search_path 固定成 wei3：就算呼叫端的 search_path 帶到 public，也不會讀寫到原本場地 ──
  for _fn in
    select p.oid::regprocedure as sig
    from pg_proc p
    where p.pronamespace = 'wei3'::regnamespace
      and p.prokind = 'f'
      and not exists (select 1 from unnest(coalesce(p.proconfig, '{}')) c where c like 'search_path=%')
  loop
    execute format('alter function %s set search_path = wei3, pg_temp', _fn.sig);
  end loop;

  grant all on all tables in schema wei3 to anon, authenticated, service_role;
  grant all on all sequences in schema wei3 to anon, authenticated, service_role;
  grant all on all routines in schema wei3 to anon, authenticated, service_role;

  -- ── 複製原本場地的「設定」（只有設定；記帳紀錄／營業日／每日帳目／帳號一律不複製）──
  -- 機台的「封存前累計」（carry_*）不複製，新場地從 0 開始（原本場地目前也都是 0）。
  insert into wei3.machines (machine_id, name, location, status, color, sort_order, note, category, icon)
  select machine_id, name, location, status, color, sort_order, note, category, icon from public.machines;
  insert into wei3.prizes (prize_id, machine_id, name, amount, sort_order, active)
  select prize_id, machine_id, name, amount, sort_order, active from public.prizes;
  insert into wei3.quick_amounts (qa_id, machine_id, type, amount, label, sort_order)
  select qa_id, machine_id, type, amount, label, sort_order from public.quick_amounts;
  insert into wei3.meter_rates (rate_id, machine_id, rate)
  select rate_id, machine_id, rate from public.meter_rates;
end
$wei3$;
